### ISSUE TITLE
老师你好，问个RN TO Native Navbar的问题

### ISSUE THREAD

**Issue by mengerpiao** [pheromone/IOS-native-and-React-native-interaction#1]
这边想要统一采用RN的navBar，所以在appdelegate创建NavController的时候隐藏了Navbar。现在从RN push 到原生的一个Controller，pop在返回来之后，默认的NavBar会出现盖住RN的Bar。请问如何控制这个bar？

**Comment by shaoting0730** [comment]
不好意思,没怎么听懂.是原生返回RN时,原生的导航条挡住了RN的导航条么?如果是这样的话,应该可以在push之后在原生里面设置原生的导航条隐藏啊.  我只是个码农,不是老师

**Comment by mengerpiao** [comment]
找到问题了，我之前有个category中的runtime控制着navbar。。。尴尬了
